apiVersion: v1
kind: Service
metadata:
  labels:
    app: dtc-zipkin
  name: dtc-zipkin
spec:
  type: NodePort # Sets service type
  ports:
    - name: "9411"
      nodePort: 31623
      port: 9411
      targetPort: 9411
      protocol: TCP
  selector:
    app: dtc-zipkin
status:
  loadBalancer: {}
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: dtc-zipkin # Labels and Selectors
#   name: dtc-zipkin-external # Sets service name
# spec:
#   type: NodePort # Sets service type
#   ports:
#     - name: "9411"
#       port: 9411
#       protocol: TCP
#   selector:
#     app: dtc-zipkin
# status:
#   loadBalancer: {}