apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: otel-collector
  name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector:0.83.0
          command:
            - "/otelcol"
            - "--config=/config/otel-collector-config.yaml"
          ports:
            - containerPort: 55679 # Default endpoint for ZPages.
            - containerPort: 4317 # Default endpoint for OpenTelemetry receiver.
            - containerPort: 14250 # Default endpoint for Jaeger gRPC receiver.
            - containerPort: 14268 # Default endpoint for Jaeger HTTP receiver.
            - containerPort: 9411 # Default endpoint for Zipkin receiver.
            - containerPort: 8888  # Default endpoint for querying metrics.
          resources: {}
          volumeMounts:
            # - name: oteldata
            #   mountPath: "/etc/output"
            - name: otel-collector-config-vol
              mountPath: /config/otel-collector-config.yaml
              subPath: otel-collector-config.yaml
      volumes:
        # - name: oteldata
        #   persistentVolumeClaim:
        #     claimName: otel-collector-pv-claim
        - name: otel-collector-config-vol
          configMap:
            name: otel-collector-config
            items:
              - key: otel.collector.config
                path: otel-collector-config.yaml
      restartPolicy: Always
status: {}
