apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  ports:
    - name: "6379"
      port: 6379
      protocol: TCP
  selector:
    app: redis
status:
  loadBalancer: {}
