kind: PersistentVolume
apiVersion: v1
metadata:
  name: seq-pv-volume  # Sets PV's name
  labels:
    type: local  # Sets PV's type to local
    app: seq
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/run/desktop/mnt/host/c/tmp/seqdata" # Specific to Desktop Docker on Windows
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: seq-pv-claim  # Sets name of PVC
  labels:
    app: seq
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 2Gi  # Sets volume size