apiVersion: v1
kind: Service
metadata:
  labels:
    app: company-microservice-membership-service # Labels and Selectors
  name: company-microservice-membership-service # Sets service name
spec:
  type: LoadBalancer # Sets service type
  ports:
    - name: "80"
      port: 80
      protocol: TCP
    # - name: "443"
    #   port: 443
    #   protocol: TCP
  selector:
    app: company-microservice-membership-service
status:
  loadBalancer: {}